language: r
sudo: false
cache: packages

os:
  - linux
  - osx
    brew_pacakges: libgit2

r:
  - release
  - devel
  - oldrel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
